- ladybug/sunpath.py
IronPython in Grasshopper was giving me errors for using -north.
> Changed -north to -1 * north

- ladybug/sunpath.py
This PR is made in response to #33
> Fixing Sunrise and SunSet Hours

- setup.py
For Travis-CI integration referenced in https://github.com/ladybug-tools/honeybee/issues/46
This setup.py ensures any pip install of the ladybug package, i.e `pip install git+git://github.com/saeranv/ladybug-1.git@master#egg=ladybug` will recursively search and install ladybug's nested modules.
> Add setup.py so that pip installing honeybee can import all modules from Ladybug

- ladybug/epw.py
import_data is not supposed to be accessed from outside the class. Resolved #50
> made _import_data internal

- .travis.yml
- ladybug/analysisperiod.py
- ladybug/color.py
- ladybug/datacollection.py
- ladybug/datatype.py
- ladybug/dt.py
- ladybug/epw.py
- ladybug/header.py
- ladybug/legendparameters.py
- ladybug/listoperations.py
- ladybug/location.py
- ladybug/psychrometrics.py
- ladybug/rootFinding.py
- ladybug/stat.py
- ladybug/sunpath.py
- ladybug/wea.py
- tox.ini
This is minimum changes that was neccessary to make ladybug work both in Python 2 and Python 3. Now we need to write more and more tests. I'm sure there are methods there that will fail in Python 3.
Resolved #47
Co-Authored-By: Christian Kongsgaard
Co-Authored-By: Antoine Dao
> Ladybug <3 Python 3!

- README.md
Now that we are supporting Python 3 let's make it explicit.
> Added badges for different versions of Python

- ladybug/wea.py
- tests/wea_test.py
Added some more Wea tests.
I also added a new property to the Wea object that I think will be useful (it's at least very useful for the tests).
@mostaphaRoudsari , let me know if you see anything glaringly wrong in the tests.
> Increasing coverage!!!

- ladybug/dt.py
- ladybug/sunpath.py
- ladybug/wea.py
- tests/sunpath_test.py
- tests/wea_test.py
- Added support for leap year to Datetime
- Added support for leap year to sunpath
- Fixed spelling mistake in method name: calculate_sun_from_date_time
> Finished adding support for leap year

- ladybug/wea.py
- tests/wea_test.py
@mostaphaRoudsari ,
I hope that you don't mind that I just merge this one in myself given that these are all things we talked about yesterday.
> Improved Wea Tests

- ladybug/analysisperiod.py
- ladybug/dt.py
- ladybug/wea.py
- tests/analysisperiod_test.py
- tests/wea_test.py
This commit finishes the development of Wea class to suppoer leap year. It was mainly neccassary to create clear skies for studies. I also cleaned the code and removed some duplicated functionalities in a single method. Other changes are:
1. Wea now accepts DataCollections and not lists. I added a classmethod to support creating Wea from list of numbers.
2. For timestep 1 the datetime is adjusted for 30 minutes for all the classmethods. The __init__ doesn't modify datetimes. This makes the class cleaner and better structured. Also the write method is now clean and doesn't have multiple checks.
> Finished supporting leap year in Wea

- .travis.yml
> fix(CI): use semantic-release publish command

- .travis.yml
- setup.py
> fix(pypi): add elucid3 as a requirement 

- .travis.yml
- setup.cfg
Check out the Travis job to see the difference.
> ci(travis): split test and deploy jobs

- .gitignore
- .travis.yml
- dev-requirements.txt
- tests/ddy/chicago_monthly.ddy
CI and package versioning FTW!
> ci(pytest): change pytest script and use dev-requirements.txt

- ladybug/__init__.py
- ladybug/_datacollectionbase.py
- ladybug/datacollection.py
- ladybug/datacollectionimmutable.py
- tests/datacollection_test.py
- tests/datacollectionimmutable_test.py
I still have to finish the tests for the immutable types, which should be pushed shortly.
> feat(datacollection): Added Immutable Types for Data Collections

- .travis.yml
- dev-requirements.txt
#125 
Told you you'd be mad when you see the fix :stuck_out_tongue:
> fix(deploy): fix travis file for docs deployment

- ladybug/__init__.py
not really! GitHub being crazy. there is no conflicts.
> fix(init): fix conflicts

- docs/conf.py
This should fix the automated documentation.
> docs(conf.py): set version in conf.py

- ladybug/_datacollectionbase.py
- ladybug/analysisperiod.py
- ladybug/color.py
- ladybug/datacollection.py
- ladybug/datatype/base.py
- ladybug/designday.py
- ladybug/dt.py
- ladybug/epw.py
- ladybug/graphic.py
- ladybug/header.py
- ladybug/legend.py
- ladybug/location.py
- ladybug/psychrometrics.py
- ladybug/stat.py
- ladybug/wea.py
- tests/analysisperiod_test.py
- tests/color_test.py
- tests/datacollection_test.py
- tests/datatype_test.py
- tests/designday_test.py
- tests/epw_test.py
- tests/graphic_test.py
- tests/legend_test.py
- tests/location_test.py
- tests/psychrometrics_test.py
- tests/stat_test.py
- tests/wea_test.py
... there are also a few minor edits to the psychrometric library  but these do not require review as it's mostly adding docstrings and tests.
> refactor(dict): Replacing to_json and from_json with to_dict and from_dict

- ladybug/_datacollectionbase.py
- ladybug/designday.py
- ladybug/stat.py
After seeing how @mostaphaRoudsari was compiling the regex strings in honeybee-radiance, I decided to make a small performance upgrade to how we used regex in ladybug core. The strings now get compiled once for each object instead of every time the method is called.
> perf(regex): Moving regex compiling out of methods

- .gitignore
- dev-requirements.txt
I updated the libraries locally and was able to create the package successfully. I'm sending the PR directly to master so we see if it is really fixing the issue.
also see: https://github.com/pypa/warehouse/issues/4079#issuecomment-420929642
fixes #149
> fix(pypi): fix deployment issue to pypi

- tests/analysisperiod_test.py
- tests/color_test.py
- tests/datacollection_test.py
- tests/datacollectionimmutable_test.py
- tests/datatype_test.py
- tests/ddy/chicago_monthly.ddy
- tests/designday_test.py
- tests/epw_test.py
- tests/futil_test.py
- tests/graphic_test.py
- tests/legend_test.py
- tests/location_test.py
- tests/psychrometrics_test.py
- tests/skymodel_test.py
- tests/stat_test.py
- tests/sunpath_test.py
- tests/wea_test.py
I needed a mindless yet mildly productive task to do for an hour while I was too tired to do real work. 
Also, after we merge this in, I think we need to re-sync development with master as I see there were a few commits that have been made directly to it.
> style(tests): Updating tests to use pytest instead of unittest

- ladybug/datatype/power.py
- ladybug/datatype/uvalue.py
Now that I am starting to implement schedule in honeybee-energy, I realized there are a few more data types that it would be useful to have in ladybug core.
> feat(datatype): Adding data types for schedule type limits

- .travis.yml
- deploy.sh
- dev-requirements.txt
- requirements.txt
- setup.py
> ci(docs): build docs in seperate step to PyPi deployment

- ladybug/analysisperiod.py
- ladybug/datatype/power.py
- ladybug/datatype/uvalue.py
- ladybug/dt.py
- ladybug/header.py
- ladybug/location.py
- ladybug/sunpath.py
- tests/dt_test.py
The development of honeybee-energy schedules is going to be much smoother if we can do a release with these features.  This also allows us to get everything back in sync after @AntoineDao pushed changes to master and I pushed changes to development.
> Package for new release

- ladybug/analysisperiod.py
- ladybug/datacollection.py
- ladybug/dt.py
- ladybug/stat.py
- tests/dt_test.py
This makes the dictionary representation of objects like DataCollections a little lighter.  It will also make the honyebee-energy Schedule dictionaries a little lighter.
> feat(datetime): Add to_array and from_array methods to datetime

- ladybug/dt.py
- tests/dt_test.py
@mostaphaRoudsari  ,
I hope that you don't mind that I just merge this one in.  It's a bug fix to my previous commit where I added the Date class and you can see that only 2 lines were changed.
> fix(date): Fix bug in Date.from_doy() classmethod

- ladybug/analysisperiod.py
- ladybug/datacollection.py
- ladybug/dt.py
- ladybug/stat.py
- tests/dt_test.py
At this point, I need the additions of the Date and Time classes in order to start the tests of honeybee-energy schedules.  So I hope that you don't mind I just merge this one in, @mostaphaRoudsari .
> Sync master with development for another release

- ladybug/_datacollectionbase.py
- ladybug/analysisperiod.py
- ladybug/color.py
- ladybug/datacollection.py
- ladybug/datatype/base.py
- ladybug/designday.py
- ladybug/dt.py
- ladybug/epw.py
- ladybug/graphic.py
- ladybug/header.py
- ladybug/legend.py
- ladybug/location.py
- ladybug/stat.py
- ladybug/wea.py
- tests/location_test.py
resolves #157 
This is my first time contributing, so please feel free to explain any obvious things I am missing in the codebase/CI setup
> refactor(dict): Add type key to to_dict() of ladybug core objects

- README.md
- docs/README.md
#153 - Updated the Derivate Work section and fixed a few typos too.
> #153: Derivative Section updated and typos

- requirements.txt
This was causing a lot of issues downstream in extensions.
> fix(requirements): Use >= instead of ==

- ladybug/futil.py
As per our recent discussion, @mostapharoudsari , I want to remove this bat_to_sh function before any other parts of Ladybug Tools make use of it (right now, there's nothing using it and it's only here because it was originally a part of the honeybee.fuitl module that this was derived from).
I am also adding a copy_file_tree method, which was useful within the installer component that I just wrote and I think will have some usefulness for us down the line.
Lastly, there are some docstring improvements.
> feat(futil): Add copy_file_tree and remove bat_to_sh

- ladybug/_datacollectionbase.py
- ladybug/datacollection.py
- ladybug/sunpath.py
- ladybug/wea.py
- tests/sunpath_test.py
1. fix daylight saving period
2. add a new method to use calculate sun from minute of the year
3. update Sun class to use ladybug.geometry
> fix(sunpath): fix daylight saving period

- ladybug/__init__.py
- ladybug/color.py
- ladybug/config.json
- ladybug/config.py
- ladybug/logutil.py
- tests/config_test.py
I added this mostly so that we use a consistent location to download EPW files to. I have verified that this module will work well on both Windows and Unix-based systems.
> feat(config, logger): Add config and logging modules

- ladybug/datatype/base.py
Mostapha recently informed me that a certain practice that I was using with imports was not recommended and I can see why now. This PR replaces this with the recommended practice.
> style(datatype): Removing non-recommended import practice

- .coveragerc
I realized this file was way out of date and so I'm updating it here.
> docs(coveralls): Update coveragerc

- tests/config_test.py
This PR is mainly for testing the CLA set-up. Let's see if it works as expected.
> style(config_test): remove unused import

- ladybug/datatype/base.py
- ladybug/dt.py
From what I can tell, this seems to be the only thing preventing us from running the plugins in Rhino 5 right now so I think these extra 3 try/excepts are worthwhile.
> feat(dt): Support DateTimes in Rhino 5

- ladybug/analysisperiod.py
- tests/analysisperiod_test.py
Updated the __eq__() method to check for the keys. I only used the parameters that were currently being evaluated in the existing __eq__() method.
> #196 add `  hash  ` and `  eq  ` functionality to all classes

- ladybug/_datacollectionbase.py
- ladybug/datacollection.py
- tests/datacollection_test.py
I realized that this will be super-useful for processing Energy simulation results.
> feat(datacollection): Add + - * / - Operators to DataCollections

- ladybug/datacollection.py
- ladybug/graphic.py
- ladybug/header.py
- ladybug/hourlyplot.py
- ladybug/legend.py
- tests/datacollection_test.py
- tests/graphic_test.py
- tests/hourlyplot_test.py
This commit adds a module to create geometry of hourly plots for any hourly DataCollection.
It also fixes a few bugs and adds a few small features to other modules that pertain to the hourly plot.
@mostaphaRoudsari ,
I think it would be helpful if you could review this PR since it will serve as a template for many of the other modules that produce climate graphics.
I still have to add tests but I've been testing it in Rhino/Grasshopper with a wide variety of cases. It's working well so I don't anticipate many changes as I write the unit tests.
> feat(hourlyplot): Add module for HourlyPlot

- ladybug/datatype/base.py
- ladybug/datatype/energy.py
- ladybug/datatype/power.py
- ladybug/hourlyplot.py
I'm realizing that this will be very helpful in regards to normalizing data by floor or surface area. I also cleaned up some of the existing docstrings.
> feat(datatype): Add property to note normalizable data types

- ladybug/color.py
- ladybug/config.json
- ladybug/config.py
- ladybug/graphic.py
- ladybug/legend.py
- tests/legend_test.py
This commit adds a ladybug_tools_folder property to the config.folders class. This is what will be used throughout the other Python libraries to determine where everything is installed.
This commit also adds a new LegendParametersCategorized class that is capable of producing colors  in discrete categories.
@mostaphaRoudsari ,
All of the changes here are in line with things we already discussed so I am just going to merge it in so that I can keep working on having the other Python libraries reference the `ladybug_tools_folder`. I just requested your review here so that you are aware of the changes. I'll send a PR to ladybug-grasshopper shortly with a categorized legend parameter component.
> feat(config): Add ladybug_tools installation folder to config

- ladybug/color.py
- ladybug/graphic.py
- ladybug/legend.py
This also adds a Colorset for the OpenStudio color scheme.
> fix(legend): Allow a segment_count of 1 to be acceptable

- ladybug/_datacollectionbase.py
- ladybug/hourlyplot.py
- ladybug/windrose.py
- tests/windrose_test.py
This module represents the windrose. This image gives an idea of the main types of representations:
Aspects that are still WIP:
- ~50% of the docstrings
- The last image, show_stack=True, show_zero=True needs to be debugged
- legend parameter needs to reflect actual histogram binning 
@chriswmackey also note that there are three functions:
> `_linspace`
> `bin_histogram_data`
> `bin_histogram_data_circular`
That I've moved out of the WindRose class. These are the three functions I mentioned that might be useful to move into the datacollection. Let me know your thoughts. 
S
> WindRose module

- dev-requirements.txt
- ladybug/windrose.py
- tests/windrose_test.py
@chriswmackey 
This PR completes the unit tests for the windrose. 
Also, you'll notice that dependabot seems to have bumped my sphinx version up a version in dev-requirements in a way that made it out of sync with the ladybug-tools master. Is that something we should be concerned about?
> test(Windrose): Add unit tests to check windrose angles.

- ladybug/_datacollectionbase.py
Adding missing line that was causing error (hopefully).
> docs(datacollection): Fixing code-block error in docs.

- ladybug/epw.py
> Added '__slots__'

- ladybug/epw.py
- ladybug/stat.py
- ladybug/wea.py
> perf(slots): Add '__slots__' to STAT object

- ladybug/datacollection.py
- ladybug/sunpath.py
- tests/sunpath_test.py
- tests/wea_test.py
I realized that this is needed for radiance skies.
> feat(sun): Add a property for sun to get azimuth including north

- ladybug/sunpath.py
- tests/sunpath_test.py
Sorry it took 3 commits for me to gt this right.
> fix(sun): Ensure Sun.azimuth_from_y_axis property is always positive

- ladybug/datatype/temperaturedelta.py
- tests/datatype_test.py
Resolves https://github.com/ladybug-tools/ladybug/issues/252
> fix(temperaturedelta): Ensure TemperatureDelta units are unique

- requirements.txt
Needed to increment the version in order to update honeybee-core.
> fix(geometry): Bump version of ladybug_geometry

- ladybug/wea.py
There were several redundant properties within the Wea schema, which was fine when all dictionaries were originating from the ladybug-core library. But, now that I have been documenting the Wea schema for radiance workflows, the schema really should be refactored to minimize the potential for conflicts and need for checks between these redundant properties.
I also added a check that the location assigned to the Wea is a Location object.
> fix(wea): Simplify Wea dictionary schema

- ladybug/__init__.py
- ladybug/_datacollectionbase.py
- ladybug/analysisperiod.py
- ladybug/compass.py
- ladybug/config.py
- ladybug/datacollection.py
- ladybug/ddy.py
- ladybug/designday.py
- ladybug/epw.py
- ladybug/graphic.py
- ladybug/hourlyplot.py
- ladybug/legend.py
- ladybug/location.py
- ladybug/psychrometrics.py
- ladybug/skymodel.py
- ladybug/stat.py
- ladybug/sunpath.py
- ladybug/wea.py
- ladybug/windrose.py
This commit doesn't change any of the performance of the code and is purely about styling.
> style(pep8): Fix various PEP8 styling issues

- ladybug/windrose.py
- tests/windrose_test.py
@chriswmackey 
cc @mostaphaRoudsari 
These are improvements to the wind rose module that the new GH component relies on. 
Changes:
- Adding more settable properties: north, different frequency controls
- Change frequency calculation to be another histogram calculation 
- Made defaults more explicit
- More detailed doc strings
- More tests
- General code clean-up/corrections
> feat(windrose): Modifying windrose for GH component.

- dev-requirements.txt
- ladybug/_datacollectionbase.py
- ladybug/analysisperiod.py
- ladybug/datacollection.py
- ladybug/datacollectionimmutable.py
- ladybug/datatype/area.py
- ladybug/datatype/distance.py
- ladybug/datatype/mass.py
- ladybug/datatype/specificenergy.py
- ladybug/datatype/temperaturetime.py
- ladybug/datatype/volume.py
- ladybug/graphic.py
- ladybug/hourlyplot.py
- ladybug/monthlychart.py
- tests/monthlychart_test.py
- tests/windrose_test.py
This commit fixes a few issues with the data collection and data type classes.
It also adds an option into the hourly plot to reverse the Y-axis.
Lastly, it adds a class for creating monthly charts from any data collection. The default ranges it uses for the axes are MUCH better than legacy given that it uses the cumulative property on the data type to decide whether the plot should start from 0.
> feat(chart): Add MonthlyChart and fix several bugs

- ladybug/windrose.py
- tests/windrose_test.py
@chriswmackey 
This PR contains the bug fix for the windmesh scaling issue I mentioned in my previous PR. The windrose is now scaling correctly with and without the calmrose. 
Also I changed the way users control the maximum frequency from them setting maximum hours, to setting number of frequency lines in the windrose plot, which should be a lot more intuitive.
> fix(windrose): Fix mesh size bug, and frequency_maximum to interval.

- ladybug/windrose.py
@chriswmackey 
Guess we pulled the trigger on that last PR too soon :/ 
This PR makes changes to the way the windrose handles zero values. Previously the component filtered out any values <= 0, since it assumed they were all wind speed values. However, this doesn't make sense if we are plotting non-speed values (i.e dry bulb). 
S
> fix(windrose): Ensure 0s not filtered out when data type isn't Speed.

- ladybug/windrose.py
- tests/windrose_test.py
@chriswmackey 
Here's the fix. I should have made sure to write a test for it the first time.
> fix(windrose): Fix prevailing wind direction getter.

- ladybug/color.py
- tests/color_test.py
This will be important for the viewer and adds the option to set-up default colors with opacity for visualization.
> feat(color): add alpha channel to Ladybug color

- ladybug/legend.py
- ladybug/location.py
- ladybug/skymodel.py
- ladybug/viewsphere.py
- ladybug/wea.py
- tests/viewsphere_test.py
This is useful in cases where we want the default color scheme of a certain type of analysis to be different from the standard Ladybug default.
> fix(legend): Add property to sense when colors are default

- ladybug/viewsphere.py
- tests/viewsphere_test.py
This will be used to give more accurate results from view-based studies.
> feat(viewsphere): Add methods to get weights of each view patch

- ladybug/viewsphere.py
- requirements.txt
I'm also adding a helpful property to ViewSphere class.
> fix(deps): bump ladybug-geometry from 1.22.4 to 1.22.5

- ladybug/graphic.py
This is really more of a fix than style but there will be another ladybug-geometry change that triggers a release before the end of today.
> style(graphic): Handle the case of geometry with 0 Y-dimension

- ladybug/datatype/time.py
I realized that this is necessary in order to represent certain energy model outputs like unmet hours.
> feat(datatype): Add data type for time

- ladybug/dt.py
- ladybug/psychchart.py
- ladybug/wea.py
- tests/psychchart_test.py
I'm also cleaning up a few docstrings
> style(psychchart): Add method to plot any point on the chart

- ladybug/_datacollectionbase.py
- ladybug/datacollection.py
- ladybug/datatype/base.py
- ladybug/datatype/energyflux.py
- ladybug/datatype/massflowrate.py
- ladybug/datatype/power.py
- ladybug/datatype/speed.py
- ladybug/datatype/temperaturedelta.py
- ladybug/datatype/volumeflowrate.py
- ladybug/psychchart.py
- tests/datacollection_test.py
This will be useful for several cases where people want to get cumulative data from data types like power.
> fix(datacollection): Add method to aggregate data over time

- ladybug/datatype/volumeflowrate.py
- ladybug/datatype/volumeflowrateintensity.py
- tests/datatype_test.py
This will be really helpful both for converting infiltration and service hot water values.
I'm also adding some volume flow rate units that are particularly helpful for water usage.
> feat(datatype): Add type for VolumeFlowRateIntensity

- ladybug/wea.py
Resolves https://github.com/ladybug-tools/ladybug/issues/369
> fix(wea): Fix misspelled isotropic

- ladybug/__main__.py
- ladybug/cli/__init__.py
- ladybug/cli/translate.py
- ladybug/climatezone.py
- ladybug/ddy.py
- ladybug/epw.py
- ladybug/wea.py
- requirements.txt
- setup.py
- tests/cli_main_test.py
- tests/cli_translate_test.py
- tests/epw_test.py
I am also refactoring all of the classes that can write to files to have a write() method for consistency (we will leave the save() method on EPW and DDY for the time being).
The code that actually generates the file contents is now its own method so we can always get the string if there's something else handling the writing-to-file (eg. a CLI that may want to print things to stdout).
Lastly, I added an EPW.from_file_string, which we can use for things like a web interface for ladybug.
CC: @mostaphaRoudsari
> feat(cli): Add a CLI and basic translation commands

- ladybug/datatype/current.py
- ladybug/datatype/mass.py
- ladybug/datatype/massflowrate.py
- ladybug/datatype/power.py
- ladybug/datatype/pressure.py
- ladybug/datatype/rvalue.py
- ladybug/datatype/specificenergy.py
- ladybug/datatype/speed.py
- ladybug/datatype/uvalue.py
- ladybug/datatype/voltage.py
- ladybug/datatype/volumeflowrateintensity.py
- ladybug/legend.py
- tests/datatype_test.py
- tests/graphic_test.py
I'm also fixing a bug in the graphic container with ordinal data types.
> fix(datatype): Add data types for voltage and current

- .dockerignore
- .github/workflows/ci.yaml
- Dockerfile
- deploy.sh
- ladybug/cli/_helper.py
- ladybug/cli/translate.py
I am also adding a new option into the epw-to-wea command.
> fix(docker): Setup auto-deployment to Dockerhub

- docs/cli.rst
- docs/cli/index.rst
- docs/conf.py
- docs/index.rst
- ladybug/epw.py
- ladybug/sunpath.py
Hi @chriswmackey,
This one was also quite simple to update. I fixed also a few docstring format warnings.
> docs(cli): Improve CLI documentation structure

- ladybug/_datacollectionbase.py
- ladybug/analysisperiod.py
- ladybug/cli/setconfig.py
- ladybug/cli/translate.py
- ladybug/datacollection.py
- ladybug/dt.py
- ladybug/header.py
- ladybug/legend.py
- ladybug/wea.py
- tests/cli_translate_test.py
- tests/datacollection_test.py
- tests/legend_test.py
- tests/wea_test.py
This commit addresses a number of minor issues including:
* Fix issue with the CLI writing a default EPW folder when its called
* Fix a bug in DateTime class for leap years
* Implement staticmethod to set Wea values to constant
* Add command to convert Wea to constant values
* Add property to enforce_on_hour to Wea
* Add a duplicate method to Wea
* Add equality check for legend par
* Ensure that shallow `copy` always has the same effect as `duplicate()`
Resolves https://github.com/ladybug-tools/ladybug/issues/356
Resolves https://github.com/ladybug-tools/ladybug/issues/195
> fix(wea): Fix a number of minor issues

- .github/workflows/ci.yaml
- .github/workflows/tests.yaml
- README.md
I also need to trigger another release to get around a Github failure.
> ci(tests): Separate tests and deployment

- ladybug/epw.py
- tests/epw_test.py
Resolves: https://github.com/ladybug-tools/ladybug/issues/513
> fix(epw): Ensure EPW.from_missing_values() uses correct dates

- ladybug/sql.py
This ensures that the individual values are parsed when the reporting frequency is annual.
> fix(sql): Ensure that Annual results can still be parsed

- ladybug/config.py
- tests/config_test.py
I am finding that I frequently need this information lower in the deps tree. So I am adding it here.
> fix(config): Expose Python information on ladybug config

- ladybug/config.py
- ladybug/sql.py
- tests/sql_test.py
I am also implementing the feature provided by Boris in this PR:
https://github.com/ladybug-tools/ladybug/pull/555
> fix(config): Implement fallback option when HOME folder is inaccessible

- ladybug/sunpath.py
- tests/sunpath_test.py
More information is here:
https://discourse.ladybug.tools/t/epw-file-error-issues-with-sunpath-1-solution-exception-hour-must-be-in-0-23-6-21-24-22-m-d-h-m/19420
> fix(sunpath): Ensure Sunpath can handle after-midnight sunsets

- ladybug/legend.py
- tests/legend_test.py
I'm also adding a method to set the color set using the name, which should be useful in apps.
> fix(legend): Add user_data to LegendParameters

- .github/workflows/ci.yaml
- .releaserc.json
- ladybug/_datacollectionbase.py
- ladybug/monthlychart.py
More info is here:
https://discourse.ladybug.tools/t/energy-balance-with-time-interval-operation/24874
> fix(monthlychart): Ensure that MonthlyPerHour data stacks nicely

- ladybug/sql.py
This may come in handy in the future if someone really messes with the run periods and the reporting intervals.
> fix(sql): Add a generic function to get all values for an output

- ladybug/cli/translate.py
- ladybug/commandutil.py
- tests/cli_translate_test.py
This commit also includes a new commandutil module that helps format CLI-like inputs for the command.
> feat(cli): Implement a standard for running CLI functions

- ladybug/color.py
- tests/color_test.py
We probably should have done this a while ago but better late than never.
> fix(color): Add methods for Color to/from hex

- ladybug/commandutil.py
- ladybug/datacollection.py
I was just finding myself copay/pasting this same code in several repos. So it seemed like it should have a place in ladybug.
> fix(commandutil): Add a function for processing CLI --output-files

- ladybug/datatype/conductance.py
- ladybug/datatype/conductivity.py
- ladybug/datatype/density.py
- ladybug/datatype/illuminance.py
- ladybug/datatype/luminance.py
- ladybug/datatype/resistance.py
- ladybug/datatype/resistivity.py
- ladybug/datatype/rvalue.py
- ladybug/datatype/specificheatcapacity.py
- ladybug/datatype/temperature.py
- ladybug/datatype/temperaturedelta.py
- ladybug/datatype/uvalue.py
- ladybug/datatype/volumeheatcapacity.py
This is needed to convert many of the inputs and outputs of EnergyPlus and DES simulations to IP.
> feat(datatype): Add several more units systems
