ladybug-tools/ladybug

ladybug/sunpath.py

These changes have mainly been directed towards improving the altitude and azimuth calculation. @mostaphaRoudsari This is my first PR for a [+] version. Kindly let me know if I am supposed to provide any other file.

Refining Sunpath

---

.travis.yml

Noticed I had forgotten to pip install `coveralls` in the travis file which is why the badge wasn't updating. Fixed it now and seems to have updated on the [coveralls.io page](https://coveralls.io/builds/17876088). Will merge with master which should hopefully update the badge accordingly.

fixed coveralls

---

ladybug/stat.py

The old version of IronPython that ships with Rhino 5 has some bugs in the platform module.  In this case, the inron_python variable does not get set at all.  To avoid this case, I set a default variable of iron_python to True before checking the platform module.

Set Default IronPython Variable for Very Old Versions

---

.travis.yml

Didn't read through your modification properly @mostaphaRoudsari and didn't notice the fact you had the command to bump version but not the command to deploy. The deploy command bumps versions and pushes to PyPi + github releases.

fix(CI): publish after bumping version

---

setup.py

Judging by the last deploy of euclid3 being 2014 I am not overly worried about breaking changes but this is a good habit to keep.
Should fix #80

fix(euclid3): enforce dependency version

---

ladybug/epw.py
tests/epw_test.py

We have forgotten to change .values to .data after making the change in DataCollection class.
Added an extra test to catch this issue in the future.

fix(epw): fixed bug in sky_temperature method

---

ladybug/_datacollectionbase.py
ladybug/datacollection.py
ladybug/datatype/base.py
ladybug/datatype/energyflux.py
ladybug/datatype/percentage.py
ladybug/datatype/rvalue.py
ladybug/datatype/thermalcondition.py
tests/datacollection_test.py

This PR consolidates the code that performs the different time interval operations on data collections (ie. average_monthly, total_daily, etc.)  It saves us from a lot of redundant code and also made it simple to implement an average_monthly, total_monthly, and percentile_monthly methods on the daily collection.
I also added a property on all data collections to track whether the data is_continuous.  This is obvious in the case of the hourly collections since there are two different objects but these methods are particularly helpful on the monthly, daily, and monthly_per_hour collections.  They essentially save us from having to make completely separate objects for continuous/discontinuous daily and monthly collections.
This PR also includes a few more changes to the datatype class in …

feat(datacollection): Consolidate Code

---

ladybug/_datacollectionbase.py
ladybug/datacollection.py
ladybug/datatype/angle.py
ladybug/datatype/base.py
ladybug/datatype/energyflux.py
ladybug/datatype/energyintensity.py
ladybug/datatype/fraction.py
ladybug/datatype/generic.py
ladybug/datatype/illuminance.py
ladybug/datatype/luminance.py
ladybug/datatype/pressure.py
ladybug/datatype/speed.py
ladybug/datatype/temperature.py
ladybug/epw.py
tests/datacollection_test.py

After realizing that the code for the epw values on the data type objects did not pass the smell test, we are putting them back on the EPW field object.  I now agree that this makes more sense and we never should have moved them.
Resolves #118

fix(datatype): Putting epw missing, min, and max valules on EPW

---

.travis.yml

Seems it's easy enough to install node on a python image but the node image's python distro doesn't
play well with https.
#125

ci(travis): use python image to deploy with semantic-release

---

docs/conf.py
ladybug/__init__.py
ladybug/_datacollectionbase.py
ladybug/legendparameters.py
ladybug/skymodel.py
ladybug/wea.py
tests/skymodel_test.py
tests/wea_test.py

This PR should set the development branch to be equal to master and also address the issue with generating docs.

fix(docs): set version to ''

---

ladybug/analysisperiod.py
ladybug/dt.py
ladybug/header.py
ladybug/location.py
ladybug/sunpath.py
tests/dt_test.py

These two objects are particularly helpful for defining EnergyPlus schedules and there may be some other places where it is helpful to have these objects coordinated with the Ladybug DateTime and AnalysisPeriod as they are here.
This commit also adds a full set of tests for DateTime, Date, and Time.  It also includes a few corrections to places where we were internally using hasattr instead of isinstance.

feat(date, time): Add objects for Date and Time

---

ladybug/_datacollectionbase.py
ladybug/datacollection.py
ladybug/legend.py
ladybug/wea.py

In Python 3.8, the option to import Iterable from collections will be deprecated in favor of `from collections.abc import Iterable`.  This commit brings ladybug into compatibility with this standard while also maintaining backwards compatibility.

feat(iterable): Update for compatibility with Python 3.8

---

ladybug/futil.py

I have found a major case where the distutils.copy_tree function fails whenever someone deletes the destination folder and then uses distutils.copy_tree to copy something to that location. The function that I am adding here has always worked for all of the cases I have tested it in.  It also saves us from having to use the prepare_dir method on the parent folder before we copy it.

feat(futil): Adding back copy_file_tree

---

ladybug/dt.py
tests/dt_test.py

Changes are made to enable the `DateTime`, `Date`, and `Time` to be pickled and unpickled. Also referencing  ladybug-tools#188

Enabling the ability for DateTime to be pickled and unpickled

---

ladybug/designday.py

The previous commit made the inclusion of Location objects in the DesignDay optional and this commit adds an argument to the `to_dict` method, allowing the user to choose whether to include it.

feat(designday): Add option to include location in DesignDay dict

---

ladybug/_datacollectionbase.py
ladybug/color.py
ladybug/datacollection.py
ladybug/datatype/base.py
ladybug/datatype/generic.py
ladybug/designday.py
ladybug/epw.py
ladybug/graphic.py
ladybug/legend.py
ladybug/skymodel.py
ladybug/stat.py
ladybug/wea.py
tests/analysisperiod_test.py
tests/datacollection_test.py
tests/datacollectionimmutable_test.py
tests/epw_test.py
tests/graphic_test.py
tests/legend_test.py
tests/sunpath_test.py

The PEP8 police should appreciate this commit. It's purely a style commit that removes all situations of `is True` and `is False` from the library, replacing them with the correct PEP8 version.

style(pep8): Remove all `is True` and `is False` cases

---

ladybug/analysisperiod.py
ladybug/designday.py
ladybug/stat.py
tests/ddy_test.py
tests/stat_test.py

I realized that the only reason why I was requesting separate inputs for month and day_of_month was because I originally wrote this class before we had Date objects in the dt module. So this commit is replacing these two inputs with a Date object and this should be less prone to errors (like invalid dates).

fix(designday): Use Date object for DesignDay

---

ladybug/designday.py
ladybug/dt.py
tests/dt_test.py

We did this in the schema for schedules and DataCollections and I think it makes sense to use it everywhere. It will be a lot more compact this way and.
This commit also changes date and time to be properties of DateTime rather than methods.

feat(designday): Change DesignDay to use 2-int arrays for Dates

---

ladybug/hourlyplot.py

I realized that the legend parameters are still mutable even if the dimensions of the chart are fixed and the values are not changing in the data collections. So this will ensure that the meshes and their colors with always align with the legend.

fix(hourlyplot): Regenerate colored mesh if user changes legend par

---

dev-requirements.txt
ladybug/_datacollectionbase.py

This PR should fix the docstring error in #239  which corrupts the histogram, histogram_circular, and linspace methods.

Docstring fix for histogram and linspace in datacollections.

---

ladybug/datatype/energyintensity.py

I realized that these come in handy during the post-processing of EnergyPlus results since there is usually a hybrid stage where the units are a combination of the honeybee Model units and the EnergyPlus SI units.

feat(energyintensity): Add support for hybrid units

---

ladybug/datatype/base.py

Slots don't seem to provide a major memory advantage at this point as they are not implemented on
child classes. There is a preference to remove them so certain functions can be overwritten by
plugins.
close #256

fix(datatype): remove slots

---

README.md
ladybug/config.py
setup.py

Since lbt-ladybug will be used as a shortcut to install ladybug with all of its extensions (eg. ladybug-comfort).
There's nothing to review here, @mostaphaRoudsari . I just wanted you to be aware that this change is underway.

feat(pypi): Change PyPI package name to ladybug-core

---

ladybug/windrose.py

@chriswmackey 
Sorry Chris, I'm adding one more PR. Currently the lengths of the wind rose 'bins' are integer multiples of the frequency intervals, and I realized this shouldn't be the case when we don't show frequency intervals and just average all the data per bin.

fix(windrose): Remove rounding of bin lengths when averaging wind_data.

---

ladybug/analysisperiod.py
ladybug/datacollection.py
ladybug/dt.py
tests/analysisperiod_test.py

This commit includes a number of performance improvements to the analysis period and (by extension) the hourly continuous data collection.  The biggest improvement comes from the fact that we can get the length of the analysis period without having to create all of the individual datetime objects (we just look at the time difference between the start and end datetimes). Also, when a case arrives that datetimes are needed, these datetimes get cached on the AnalysisPeriod object instead of regenerating them every time that they are called. This should dramatically cut down on the number of datetime objects that we are storing in memory at a given time.
The improvement is good enough that I can even notice the tests running faster.
Technically, there's also a bug fix in this commit but it …

perf(analysisperiod) Improve performance of AnalysisPeriod datetimes

---

ladybug/_datacollectionbase.py
ladybug/datacollection.py
ladybug/epw.py
tests/datacollection_test.py
tests/epw_test.py

This commit adds a method to the EPW class that can derive a DDY from the EPW file. The DDYs produced by this method are not as representative of the climate as the ones distributed with the EPWs but this will help a lot when running energy simulations with EPW files that have no design associated with them.
I also changed the name of a few methods that start with `get_` that aren't being used by anything that I know if right now. It's better to change this now before we start doing more with these methods.
Resolves https://github.com/ladybug-tools/ladybug/issues/308

feat(epw): Add method to derive DDY from EPW

---

ladybug/wea.py
tests/wea_test.py

I had taken these methods out with the last PR since I thought they were only being used internally in the Wea class. Also, they were mostly geared towards annual Weas, and they were not very well named (starting with get_). Now that I realized that they are used all over honeybee-radiance, I am putting them back in a way that they will still work with the new discontinuous Wea capabilities.
I also fixed a bug in the from_file method when it's used with a discontinuous Wea.
FYI @mostaphaRoudsari

fix(wea): Put back get_irradiance_value methods

---

ladybug/_datacollectionbase.py
ladybug/windrose.py
tests/datacollection_test.py
tests/windrose_test.py

@chriswmackey 
Found two errors while comparing this windrose to the legacy component. This PR includes the following changes:
-  An error in the histogram_circular method. The method doesn't check the equality of the lower bound range when the bin is centered at 0.  
- Deals with duplication in epw wind direction values (0, and 360).
- Moved the histogram, histogram_circular, and linspace tests from the windrose_test module to the datacollection_test module.

fix(windrose): Correct histogram_circular lower bound binning at north direction.

---

ladybug/_datacollectionbase.py
ladybug/datacollection.py
ladybug/datacollectionimmutable.py
ladybug/datatype/time.py
ladybug/header.py
tests/datacollection_test.py
tests/datatype_test.py

This is going to make certain post-processing work with datacollections of energy results so much cleaner.
I also fixed a bug in the Time data type thanks to tests that I added.
I also made the arithmetic operations with data collections duplicate the header such that any edits of that header's metadata don't edit the original.
Lastly, I made the metadata of the header set-able given that this doesn't break anything like how setting data types could break some things.

fix(datacollection): Add method to normalize data by area

---

ladybug/windrose.py
tests/windrose_test.py

I realized there were some issues with the way that the wind rose was treating legend parameters. Notably, legend parameters are purely to manage user input and they should never be edited directly by a ladybug-core class. Otherwise, that class can end up mutating the legend parameters, which might be used by other objects.
Also, the wind rose should always default to returning the graphic container's parameters instead of its own.
Resolves https://github.com/ladybug-tools/ladybug/issues/377

fix(windrose): Fix several issues RE: WindRose and LegendParameters

---

ladybug/_datacollectionbase.py
ladybug/datacollection.py

I was getting cases of MonthlyCollections with BaseCollection type keys.

fix(datacollection): Ensure type key always matches the collection type

---

ladybug/analysisperiod.py
ladybug/datacollection.py
tests/datacollection_test.py

I realized that the current MonthlyPerHour collection could only handle timesteps of 1.  This commit fixes this such that finer timesteps are now acceptable.

fix(datacollection): Allow MonthlyPerHour to support timesteps

---

tests/futil_test.py

Now that we run so many tests, it fails pretty regularly because of the internet.

style(tests): Remove tests that depends on internet connection

---

ladybug/climatezone.py
ladybug/epw.py
tests/epw_test.py

This is going to be extremely helpful for the case that the STAT file doesn't have any climate zone data. Now, people will be able to get the right climate zone number so that they can pick a good default construction set for their energy models.

feat(climatezone): Add module for computing climate zone classifications

---

ladybug/analysisperiod.py
ladybug/cli/_helper.py
ladybug/cli/translate.py
tests/cli_translate_test.py

I realized that the AnalysisPeriod object already has all of its properties within its string representation. So just having people pass a string of an analysis period to the CLI will be much cleaner. And it allows us to get around the fact that queenbee does not support conditional artifacts.

fix(cli): Replace hacky use of analysis period JSON with string

---

ladybug/sql.py

This should ensure the data is in the correct order when the OpenStudio reporting measure adds extra outputs.

fix(sql): Ensure SQL data is sorted by time index

---

ladybug/epw.py

The term for "weather_data_file_units" is being written out as "weather_data_file_unit". This causes dctimestep to raise an error.
Before the fix: 
After the fix:

fix(epw): Fixed a bug in the EPW.to_wea header

---

ladybug/epw.py

This seems like a more elegant solution, which will work for all characters that might exist in an EPW (not just the latin ones).

fix(epw): Try using errors='ignore' instead of guessing encoding

---

ladybug/config.py

This way, if a user has Pollination installed in its default location, the resources of the plugin (like the honeybee-openstudio-gem) can still be used.

fix(config): Enable core libraries to use Pollination plugin resources

---

ladybug/epw.py
ladybug/graphic.py
ladybug/legend.py

We have come to see this as a hack that we didn't really need. Instead people should use the VisualizationSet object in ladybug-display.

fix(graphic): Remove optional geometry from GraphicContainer

---

ladybug/legend.py

I didn't realize that JSON will turn all dictionary keys into strings. This addresses this upon re-serialization.

fix(legend): Fix bug when serializing ordinal dict from JSON

---

ladybug/config.py

Adds a check to [config.py | Folders._find_default_ladybug_tools_folder()](https://github.com/ladybug-tools/ladybug/blob/25f88a22b1ca9adfa2ad6ee77711746ff6b12361/ladybug/config.py#L251) method to ensure that if the 'ladybug_tools' folder already exists on the user's computer, we don't try and create it again (which would raise an OS Error / WinError 183)
- See discussion here [link](https://3.basecamp.com/4298486/buckets/24461086/messages/6106616191) for background on the issue.
- All existing tests pass, but I did know how to add new tests for this without editing folders on the user's computer, which did not seem like the right path?

fix(config): Check for home folder during init

---

requirements.txt

This change makes Ladybug Tools compatible with Pyodide and py.cafe. currently this requirement creates conflict between the two.

fix(deps): bump click from 8.1.3 to 8.1.7
